spring:
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: docker
      password: password
      database: assigment
      port: 27017
      host: localhost
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: samganira
    password: Sabah2019
    driver-class-name: org.postgresql.Driver
